#!/bin/sh

echo 'This is TDM, a tiny display manager.'
echo 'Please select a session.'

if [ -d ${SESSIONS} ]; then
	echo -n "list of X sessions:"
	if [[ -n ${SDEFAULT} ]]; then
		echo "(default $(basename ${SDEFAULT}))"
	else
		echo
	fi

	for script in "${SESSIONS}"/*; do
		if [ -x "${script}" ]; then
			xsessions[$XID]="${script}"
			echo "$XID $(basename ${script})"
			let XID=$(($XID+1))
			let TOTAL=$(($TOTAL+1))
		fi
	done
else
	echo "${SESSIONS} doesn't exist."
	echo "making this directory."
	mkdir -p ${SESSIONS}
fi

if [ -d ${EXTRA} ]; then
	echo "others:"
	for script in "${EXTRA}"/*; do
		if [ -x "${script}" ]; then
			xsessions[$TOTAL]="${script}"
			echo "$TOTAL $(basename ${script})"
			let TOTAL=$(($TOTAL+1))
		fi
	done
fi

if [ $TOTAL -eq 0 ]; then
	fallback "No sessions found."
fi

echo -n "Session id:"
read sid

