#!/bin/sh

# TDM, tbk display manager, or tiny display manager,
# is a session selector after login.
# It links the starting script to default and start
# the startx script.

# directory settings
CONFDIR="$HOME/.tdm"
SESSIONS=${CONFDIR}/sessions
EXTRA=${CONFDIR}/extra
PREFIX=

fallback(){
	if [[ -n $1 ]]; then
		echo -e "\033[31;1m$1\033[0m"
	fi
	exec $SHELL
}

# started from startx, so start session
if [[ -n $1 && $1 = "--xstart" ]]; then
	if [[ -n ${TLOCALE} ]]; then
		export LANG=${TLOCALE}
	fi
	exec "${CONFDIR}/default"
fi

clear #clear screen

# check for a 'good' tty
(basename $(tty)|grep -q tty) || fallback "Invalid tty"

# X started, exit
if [ $(pgrep -c X) -ne 0 ]; then
	fallback 'X started.'
fi

# build the directory tree if not exist
if [[ ! -d "${CONFDIR}" ]]; then
	cp -Rv "${PREFIX}/share/tdm" "${CONFDIR}"
fi

# otherwise, run as the session chosen script
# load tdminit
if [[ -f "${CONFDIR}/tdminit" ]]; then
	source "${CONFDIR}/tdminit"
fi

if [[ -x "${CONFDIR}/default" ]]; then
	SDEFAULT=$(readlink "${CONFDIR}/default")
else
	SDEFAULT=
fi

echo 'This is TDM, a tiny display manager.'
echo 'Please select a session.'

let XID=0
let TOTAL=0
xsessions=()

if [ -d ${SESSIONS} ]; then
	echo -n "list of X sessions:"
	if [[ -n ${SDEFAULT} ]]; then
		echo "(default $(basename ${SDEFAULT}))"
	else
		echo
	fi

	for script in "${SESSIONS}"/*; do
		if [ -x "${script}" ]; then
			xsessions[$XID]="${script}"
			echo "$XID $(basename ${script})"
			let XID=$(($XID+1))
			let TOTAL=$(($TOTAL+1))
		fi
	done
else
	echo "${SESSIONS} doesn't exist."
	echo "making this directory."
	mkdir -p ${SESSIONS}
fi

if [ -d ${EXTRA} ]; then
	echo "others:"
	for script in "${EXTRA}"/*; do
		if [ -x "${script}" ]; then
			xsessions[$TOTAL]="${script}"
			echo "$TOTAL $(basename ${script})"
			let TOTAL=$(($TOTAL+1))
		fi
	done
fi

if [ $TOTAL -eq 0 ]; then
	fallback "No sessions found."
fi

echo -n "Session id:"
read sid

if [[ (-n $sid) && ($sid -lt $TOTAL) && ($sid -ge $XID) ]]; then
	exec ${xsessions[$sid]}
elif [[ (-n $sid) && ($sid -lt $XID) && ($sid -ge 0) ]]; then
	ln -sf ${xsessions[${sid}]} "${CONFDIR}/default"
	startx
	logout
else
	echo "Unknown value,load default."
	if [ -x "${CONFDIR}/default" ]; then
		startx
		logout
	else
		fallback "Session not defined,fallback."
	fi
fi

